services:
  db:
    container_name: django-play-db
    image: postgres:16
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: django_play_db
      POSTGRES_PASSWORD: secure-password
      POSTGRES_USER: django-play-user
