services:
  db:
    container_name: django-play-db
    image: postgres:13
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: db
      POSTGRES_HOST_AUTH_METHOD: trust
